#!/usr/bin/env python3
# coding: utf-8
"""Compare Python reference outcome vs Rust reference for P0-01 differential seams.

Layout (see differential/README.md):
- references/{seam}.json     — Rust baseline (generated by cargo test with AH_REFGEN=1)
- differential/out/python/{seam}.json — independent Python outcome (differential/run_python.py)

Rules:
- A case mismatch that the fixture marks ``known_divergence`` is reported as a
  KNOWN divergence (non-fatal): it documents a real Python/Rust semantic gap
  that must be closed for parity.
- Any other mismatch is fatal: exit code 1.
- The summary records both agent-harness HEAD and agent-core HEAD so CI logs
  pin the compared revisions.

Usage:
    python differential/compare.py [seam ...]   # default: all seams under differential
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
FIXTURES = REPO / "fixtures"
REFERENCES = REPO / "references"
PY_OUT = HERE / "out" / "python"

SEAMS = [
    "stop_condition",
    "messager_inprocess",
    "llm_retry",
    "tool_retry",
    "task_completion",
    "task_planning",
    "task_lifecycle",
    "subagents",
]


def git_head(repo: Path) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
        )
        return out.stdout.strip() or "unknown"
    except Exception:  # pragma: no cover - env without git
        return "unknown"


def known_divergence_names(fixture: dict) -> set[str]:
    return {
        case["name"]
        for case in fixture.get("cases", [])
        if case.get("known_divergence")
    }


def compare_seam(name: str) -> tuple[int, int, list[str]]:
    """Returns (matched, known, mismatch_descriptions)."""
    fixture = json.loads((FIXTURES / f"{name}.json").read_text(encoding="utf-8"))
    rust = json.loads((REFERENCES / f"{name}.json").read_text(encoding="utf-8"))
    py = json.loads((PY_OUT / f"{name}.json").read_text(encoding="utf-8"))
    known = known_divergence_names(fixture)
    if rust.get("seam") != py.get("seam"):
        raise SystemExit(f"[compare] seam mismatch in {name}: {rust.get('seam')} vs {py.get('seam')}")

    rust_cases = {c["name"]: c for c in rust.get("cases", [])}
    py_cases = {c["name"]: c for c in py.get("cases", [])}
    matched = 0
    known_count = 0
    mismatches: list[str] = []
    for cname in sorted(set(rust_cases) | set(py_cases)):
        if cname not in rust_cases:
            mismatches.append(f"{name}/{cname}: missing in Rust reference")
            continue
        if cname not in py_cases:
            mismatches.append(f"{name}/{cname}: missing in Python outcome")
            continue
        r, p = rust_cases[cname], py_cases[cname]
        # strip the known_divergence marker from both before comparing bodies
        r = {k: v for k, v in r.items() if k != "known_divergence"}
        p = {k: v for k, v in p.items() if k != "known_divergence"}
        if r == p:
            matched += 1
            continue
        if cname in known:
            known_count += 1
            print(f"[compare] KNOWN divergence  {name}/{cname}")
        else:
            mismatches.append(f"{name}/{cname}:\n  rust:   {json.dumps(r, ensure_ascii=False)}\n  python: {json.dumps(p, ensure_ascii=False)}")
    return matched, known_count, mismatches


def main() -> int:
    seams = sys.argv[1:] or SEAMS
    total_matched = 0
    total_known = 0
    all_mismatches: list[str] = []
    for name in seams:
        if not (PY_OUT / f"{name}.json").exists():
            print(f"[compare] missing Python outcome for {name} (run differential/run_python.py)",
                  file=sys.stderr)
            return 2
        matched, known, mismatches = compare_seam(name)
        total_matched += matched
        total_known += known
        all_mismatches.extend(mismatches)
        print(f"[compare] {name}: {matched} matched, {known} known divergence, {len(mismatches)} mismatch")

    print(f"[compare] agent-harness HEAD: {git_head(REPO)}")
    core = REPO.parent / "agent-core"
    print(f"[compare] agent-core    HEAD: {git_head(core)}")

    for m in all_mismatches:
        print(f"[compare] MISMATCH {m}")
    if all_mismatches:
        print(f"[compare] FAILED: {len(all_mismatches)} unexpected mismatch(es)", file=sys.stderr)
        return 1
    print(f"[compare] OK: {total_matched} case(s) matched, {total_known} known divergence(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
