#!/usr/bin/env bash
# P0-01 Python/Rust differential — full pipeline.
#
# Requires:
#   AGENT_CORE_ROOT  — path to the agent-core (Python) checkout (HEAD pinned by compare)
#   python 3.11+     — with pydantic installed (only external dep for current seams)
#   rust toolchain   — for the Rust reference test
#
# Steps:
#   1. Rust reference (check mode): asserts committed references/{seam}.json still
#      match current Rust behavior (regression reference; never regenerated by Python).
#   2. Python reference runner: drives the real openjiuwen implementation from the
#      same language-neutral fixtures -> differential/out/python/{seam}.json.
#   3. Compare: deep-diff both; known_divergence cases are reported, unexpected
#      mismatches fail the run.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -z "${AGENT_CORE_ROOT:-}" ]; then
  echo "AGENT_CORE_ROOT must point to the agent-core (Python) checkout" >&2
  exit 2
fi
if [ ! -d "$AGENT_CORE_ROOT/openjiuwen" ]; then
  echo "AGENT_CORE_ROOT does not look like an agent-core checkout: $AGENT_CORE_ROOT" >&2
  exit 2
fi
AGENT_CORE_ROOT=$(cd "$AGENT_CORE_ROOT" && pwd)

PYTHON="${PYTHON:-python3}"

echo "== [1/3] Rust reference (check mode) =="
cargo test -p ah-app --test differential -- --nocapture

echo "== [2/3] Python reference runner =="
AGENT_CORE_ROOT="$AGENT_CORE_ROOT" "$PYTHON" differential/run_python.py

echo "== [3/3] compare Python outcome vs Rust reference =="
"$PYTHON" differential/compare.py

echo "== differential OK =="
